<html>
    <body>
      <div>
             <strong>Dear $subject.name$</strong>,<br><br>
             It seems that you have left an AWS instance running after working hours.<br><br>
             It will stop in about 15 minutes without further warning.<br><br>
             If it is absolutely vital that this instance is kept running, please do send an email with the subject:<br>
             <strong>Please keep my instance: $instance.instanceId$ running</strong><br>
             to newman@gigaspaces.com<br><br>
             <strong>
             Your obedient servant,<br>
             Newman.
             </strong>
        </div>
     </body>
</html>