<html>
    <body>
      <div>
             Dear $subject.name$,
             It seems that you have left an AWS instance running after working hours.
             This is the last warning before instance is stopped !!!
             If it is absolutely vital that this instance is kept running please do send email with the subject: 'Please keep my instance: $instance.instanceId$ running'
             Yours truly, Newman.
        </div>
     </body>
</html>